# Generated by Django 4.1 on 2024-06-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Readings",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("time", models.DateTimeField()),
                ("temperature", models.FloatField()),
                ("humidity", models.FloatField()),
            ],
        ),
    ]
